'use client';

import Link from 'next/link';
import { SITE } from '@/lib/site';
import { Fragment, useState } from 'react';
import './pricing.css';

const FAQ: [string, string][] = [
  ['Are prices billed monthly or annually?', 'All Trevio plans are billed annually in QAR. You can add seats or add-ons at any time and they’re prorated for the rest of your term.'],
  ['Is there a free trial?', 'Yes — every plan starts with a 14-day free trial with full features, so your team can connect channels and test AI before committing.'],
  ['What counts as an AI response?', 'Any reply generated by the AI Agent or Copilot that is sent to a customer. Suggestions an agent doesn’t send are not counted.'],
  ['Can I change plans later?', 'Absolutely. Upgrade at any time and we’ll credit the unused portion of your current plan. Downgrades take effect at renewal.'],
  ['Do you help with WhatsApp Business API setup?', 'Yes. Our Doha team handles verification, number migration and template approvals as part of onboarding on every plan.'],
];

export function PricingView() {
  const [open, setOpen] = useState(0);
  const faqs = FAQ.map(([q, a], i) => ({
    q,
    a,
    id: `faq-${i}`,
    open: open === i,
    rot: open === i ? 'rotate(180deg)' : 'none',
    chevBg: open === i ? 'rgba(27,206,207,0.12)' : 'transparent',
    toggle: () => setOpen((o) => (o === i ? -1 : i)),
  }));

  return (
    <>
      <section style={{ padding: 'clamp(72px,9vw,120px) 0 clamp(40px,5vw,64px)', background: '#FFFFFF' }}>
        <div
          style={{
            maxWidth: 820,
            margin: '0 auto',
            padding: '0 24px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            textAlign: 'center',
            gap: 20,
          }}
        >
          <span
            style={{
              fontSize: 13,
              fontWeight: 700,
              letterSpacing: '0.12em',
              textTransform: 'uppercase',
              background: 'linear-gradient(90deg,#5B247A,#1BCECF)',
              WebkitBackgroundClip: 'text',
              backgroundClip: 'text',
              color: 'transparent',
            }}
          >
            Pricing
          </span>
          <h1
            style={{
              margin: 0,
              fontSize: 'clamp(40px,5.4vw,68px)',
              lineHeight: 1.05,
              letterSpacing: '-0.04em',
              fontWeight: 800,
              textWrap: 'balance',
            }}
          >
            {'Simple, '}
            <span
              style={{
                background: 'linear-gradient(90deg,#5B247A 0%,#8378FF 50%,#1BCECF 100%)',
                WebkitBackgroundClip: 'text',
                backgroundClip: 'text',
                color: 'transparent',
              }}
            >
              Transparent Pricing
            </span>
          </h1>
          <p
            style={{ margin: 0, maxWidth: 600, fontSize: 'clamp(17px,1.5vw,19px)', lineHeight: 1.65, color: '#6B7280', textWrap: 'pretty' }}
          >
            One platform for every channel, with AI built in. Pick the plan that fits your team today and upgrade whenever you’re ready.
          </p>
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8, fontSize: 13.5, color: '#6B7280' }}>
            <svg
              width="15"
              height="15"
              viewBox="0 0 24 24"
              fill="none"
              stroke="#1BCECF"
              strokeWidth="2.2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M8 2v4M16 2v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z"></path>
            </svg>
            All plans are billed annually in Qatari Riyal (QAR).
          </span>
        </div>
      </section>
      <section style={{ padding: 'clamp(24px,3vw,40px) 0 clamp(88px,10vw,128px)', background: '#FFFFFF' }}>
        <div
          className="pr-plans"
          style={{
            maxWidth: 1180,
            margin: '0 auto',
            padding: '0 24px',
            display: 'grid',
            gap: 24,
            alignItems: 'center',
          }}
        >
          <div
            style={{
              order: 1,
              borderRadius: 18,
              border: '1px solid #E8E9EF',
              background: '#fff',
              boxShadow: '0 2px 8px rgba(26,26,46,0.04),0 20px 40px -32px rgba(26,26,46,0.3)',
              padding: '34px 30px',
              display: 'flex',
              flexDirection: 'column',
              gap: 24,
            }}
          >
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              <span style={{ fontSize: 19, fontWeight: 800 }}>Startup</span>
              <span style={{ fontSize: 14.5, color: '#6B7280', lineHeight: 1.55 }}>For small teams bringing their channels together.</span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
                <span style={{ fontSize: 18, fontWeight: 700, color: '#6B7280' }}>QAR</span>
                <span style={{ fontSize: 52, fontWeight: 800, letterSpacing: '-0.04em', lineHeight: 1 }}>3,600</span>
              </div>
              <span style={{ fontSize: 14, color: '#6B7280' }}>per year</span>
            </div>
            <div style={{ height: 1, background: '#EEF0F4' }}></div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 13, fontSize: 15, lineHeight: 1.45 }}>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                3 agent seats
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                All channels in one shared inbox
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                1,000 AI responses / month
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                Basic chatbot builder
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                Contacts, labels and notes
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                Email support
              </span>
            </div>
            <a
              className="hv-outline"
              href={SITE.signUpUrl}
              style={{
                marginTop: 'auto',
                height: 50,
                borderRadius: 12,
                border: '1.5px solid #D8D6EE',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: 700,
                color: '#1A1A2E',
                whiteSpace: 'nowrap',
              }}
            >
              Start with Startup
            </a>
          </div>
          <div
            className="pr-growth"
            style={{
              position: 'relative',
              borderRadius: 20,
              border: '2px solid transparent',
              background:
                'linear-gradient(180deg,#F7F5FF,#F0FAFD) padding-box,linear-gradient(135deg,#5ED6F7,#8378FF 55%,#5B247A) border-box',
              boxShadow: '0 36px 70px -30px rgba(131,120,255,0.6)',
              display: 'flex',
              flexDirection: 'column',
              gap: 24,
            }}
          >
            <span
              style={{
                position: 'absolute',
                top: -15,
                left: '50%',
                transform: 'translateX(-50%)',
                padding: '6px 14px',
                borderRadius: 999,
                background: 'linear-gradient(100deg,#5B247A,#8378FF 60%,#5ED6F7)',
                color: '#fff',
                fontSize: 12.5,
                fontWeight: 800,
                whiteSpace: 'nowrap',
                boxShadow: '0 8px 20px -8px rgba(131,120,255,0.8)',
              }}
            >
              Most Popular
            </span>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              <span style={{ fontSize: 19, fontWeight: 800 }}>Growth</span>
              <span style={{ fontSize: 14.5, color: '#6B7280', lineHeight: 1.55 }}>For scaling teams putting AI to work.</span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
                <span style={{ fontSize: 18, fontWeight: 700, color: '#8378FF' }}>QAR</span>
                <span
                  style={{
                    fontSize: 60,
                    fontWeight: 800,
                    letterSpacing: '-0.045em',
                    lineHeight: 1,
                    background: 'linear-gradient(90deg,#5B247A,#8378FF)',
                    WebkitBackgroundClip: 'text',
                    backgroundClip: 'text',
                    color: 'transparent',
                  }}
                >
                  9,600
                </span>
              </div>
              <span style={{ fontSize: 14, color: '#6B7280' }}>per year</span>
            </div>
            <div style={{ height: 1, background: 'rgba(131,120,255,0.22)' }}></div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 13, fontSize: 15, lineHeight: 1.45 }}>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start', fontWeight: 700 }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                Everything in Startup, plus
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                10 agent seats
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                10,000 AI responses / month
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                AI Agent and Copilot
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                Advanced broadcasting and A/B tests
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                WhatsApp Commerce and Mini Apps
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                SLA management and analytics
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                Priority support
              </span>
            </div>
            <a
              className="hv-bright"
              href={SITE.signUpUrl}
              style={{
                marginTop: 'auto',
                height: 52,
                borderRadius: 12,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: 800,
                color: '#fff',
                whiteSpace: 'nowrap',
                background: 'linear-gradient(100deg,#5B247A,#8378FF 70%,#5ED6F7 140%)',
                boxShadow: '0 14px 28px -12px rgba(91,36,122,0.7)',
              }}
            >
              Choose Growth
            </a>
          </div>
          <div
            style={{
              order: 3,
              borderRadius: 18,
              border: '1px solid #E8E9EF',
              background: '#fff',
              boxShadow: '0 2px 8px rgba(26,26,46,0.04),0 20px 40px -32px rgba(26,26,46,0.3)',
              padding: '34px 30px',
              display: 'flex',
              flexDirection: 'column',
              gap: 24,
            }}
          >
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              <span style={{ fontSize: 19, fontWeight: 800 }}>Premium</span>
              <span style={{ fontSize: 14.5, color: '#6B7280', lineHeight: 1.55 }}>For larger organisations with advanced needs.</span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
                <span style={{ fontSize: 18, fontWeight: 700, color: '#6B7280' }}>QAR</span>
                <span style={{ fontSize: 52, fontWeight: 800, letterSpacing: '-0.04em', lineHeight: 1 }}>21,600</span>
              </div>
              <span style={{ fontSize: 14, color: '#6B7280' }}>per year</span>
            </div>
            <div style={{ height: 1, background: '#EEF0F4' }}></div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 13, fontSize: 15, lineHeight: 1.45 }}>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start', fontWeight: 700 }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                Everything in Growth, plus
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                25 agent seats
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                Unlimited AI responses (fair use)
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                MCP Connector and Conversion CAPI
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                SSO, audit logs and roles
              </span>
              <span style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <svg
                  style={{ flex: 'none', marginTop: 2 }}
                  width="18"
                  height="18"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#1BCECF"
                  strokeWidth="2.6"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M20 6 9 17l-5-5"></path>
                </svg>
                Dedicated success manager
              </span>
            </div>
            <a
              className="hv-navy"
              href={SITE.signUpUrl}
              style={{
                marginTop: 'auto',
                height: 50,
                borderRadius: 12,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontWeight: 700,
                color: '#fff',
                whiteSpace: 'nowrap',
                background: '#1A1A2E',
              }}
            >
              Go Premium
            </a>
          </div>
        </div>
      </section>
      <section
        style={{
          padding: 'clamp(80px,10vw,120px) 0',
          background: '#F8F9FB',
          borderTop: '1px solid #EEF0F4',
          borderBottom: '1px solid #EEF0F4',
        }}
      >
        <div style={{ maxWidth: 1240, margin: '0 auto', padding: '0 24px', display: 'flex', flexDirection: 'column', gap: 48 }}>
          <div
            style={{
              maxWidth: 640,
              margin: '0 auto',
              textAlign: 'center',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              gap: 14,
            }}
          >
            <span
              style={{
                fontSize: 13,
                fontWeight: 700,
                letterSpacing: '0.12em',
                textTransform: 'uppercase',
                background: 'linear-gradient(90deg,#5B247A,#1BCECF)',
                WebkitBackgroundClip: 'text',
                backgroundClip: 'text',
                color: 'transparent',
              }}
            >
              Add-ons
            </span>
            <h2 style={{ margin: 0, fontSize: 'clamp(30px,3.8vw,46px)', lineHeight: 1.1, letterSpacing: '-0.035em', fontWeight: 800 }}>
              Extend Your Plan.
            </h2>
            <p style={{ margin: 0, fontSize: 16.5, lineHeight: 1.65, color: '#6B7280' }}>Add exactly what you need, on any plan.</p>
          </div>
          <div className="pr-addons" style={{ display: 'grid', gap: 16 }}>
            <div
              style={{
                padding: 22,
                borderRadius: 14,
                background: '#fff',
                border: '1px solid #E6E7EE',
                display: 'flex',
                flexDirection: 'column',
                gap: 12,
              }}
            >
              <span
                style={{
                  width: 42,
                  height: 42,
                  borderRadius: 12,
                  background: 'linear-gradient(135deg,#5ED6F7,#8378FF)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#fff"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM19 8v6M22 11h-6"></path>
                </svg>
              </span>
              <span style={{ fontSize: 16, fontWeight: 700 }}>Extra agent seats</span>
              <span style={{ fontSize: 14, lineHeight: 1.55, color: '#6B7280' }}>Grow your team one seat at a time.</span>
            </div>
            <div
              style={{
                padding: 22,
                borderRadius: 14,
                background: '#fff',
                border: '1px solid #E6E7EE',
                display: 'flex',
                flexDirection: 'column',
                gap: 12,
              }}
            >
              <span
                style={{
                  width: 42,
                  height: 42,
                  borderRadius: 12,
                  background: 'linear-gradient(135deg,#5ED6F7,#8378FF)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#fff"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M9.94 15.5A2 2 0 0 0 8.5 14.06l-6.13-1.58a.5.5 0 0 1 0-.96L8.5 9.94A2 2 0 0 0 9.94 8.5l1.58-6.13a.5.5 0 0 1 .96 0L14.06 8.5A2 2 0 0 0 15.5 9.94l6.13 1.58a.5.5 0 0 1 0 .96L15.5 14.06a2 2 0 0 0-1.44 1.44l-1.58 6.13a.5.5 0 0 1-.96 0z"></path>
                </svg>
              </span>
              <span style={{ fontSize: 16, fontWeight: 700 }}>AI response packs</span>
              <span style={{ fontSize: 14, lineHeight: 1.55, color: '#6B7280' }}>Top up AI replies for busy seasons.</span>
            </div>
            <div
              style={{
                padding: 22,
                borderRadius: 14,
                background: '#fff',
                border: '1px solid #E6E7EE',
                display: 'flex',
                flexDirection: 'column',
                gap: 12,
              }}
            >
              <span
                style={{
                  width: 42,
                  height: 42,
                  borderRadius: 12,
                  background: 'linear-gradient(135deg,#5ED6F7,#8378FF)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#fff"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z"></path>
                </svg>
              </span>
              <span style={{ fontSize: 16, fontWeight: 700 }}>WhatsApp Calls</span>
              <span style={{ fontSize: 14, lineHeight: 1.55, color: '#6B7280' }}>Voice calling with recordings and AI summaries.</span>
            </div>
            <div
              style={{
                padding: 22,
                borderRadius: 14,
                background: '#fff',
                border: '1px solid #E6E7EE',
                display: 'flex',
                flexDirection: 'column',
                gap: 12,
              }}
            >
              <span
                style={{
                  width: 42,
                  height: 42,
                  borderRadius: 12,
                  background: 'linear-gradient(135deg,#5ED6F7,#8378FF)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#fff"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M2 3h20v14H2zM8 21h8M12 17v4"></path>
                </svg>
              </span>
              <span style={{ fontSize: 16, fontWeight: 700 }}>Additional numbers</span>
              <span style={{ fontSize: 14, lineHeight: 1.55, color: '#6B7280' }}>Connect more WhatsApp numbers or brands.</span>
            </div>
            <div
              style={{
                padding: 22,
                borderRadius: 14,
                background: '#fff',
                border: '1px solid #E6E7EE',
                display: 'flex',
                flexDirection: 'column',
                gap: 12,
              }}
            >
              <span
                style={{
                  width: 42,
                  height: 42,
                  borderRadius: 12,
                  background: 'linear-gradient(135deg,#5ED6F7,#8378FF)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="#fff"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path d="M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20zM12 16v-4M12 8h.01"></path>
                </svg>
              </span>
              <span style={{ fontSize: 16, fontWeight: 700 }}>{'Onboarding & training'}</span>
              <span style={{ fontSize: 14, lineHeight: 1.55, color: '#6B7280' }}>Hands-on setup by our Doha team.</span>
            </div>
          </div>
        </div>
      </section>
      <section style={{ padding: 'clamp(64px,8vw,96px) 0', background: '#FFFFFF' }}>
        <div style={{ maxWidth: 880, margin: '0 auto', padding: '0 24px' }}>
          <div
            style={{
              borderRadius: 16,
              border: '1px solid rgba(27,206,207,0.35)',
              background: 'rgba(27,206,207,0.06)',
              padding: 'clamp(24px,3.5vw,36px)',
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              textAlign: 'center',
              gap: 14,
            }}
          >
            <span
              style={{
                width: 44,
                height: 44,
                borderRadius: '50%',
                background: 'rgba(27,206,207,0.14)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <svg
                width="22"
                height="22"
                viewBox="0 0 24 24"
                fill="none"
                stroke="#0B8F90"
                strokeWidth="2.2"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20zM12 16v-4M12 8h.01"></path>
              </svg>
            </span>
            <span style={{ fontSize: 18, fontWeight: 800 }}>Third-party costs are billed separately</span>
            <p style={{ margin: 0, fontSize: 15, lineHeight: 1.7, color: '#4B5163', maxWidth: 680, textWrap: 'pretty' }}>
              Plan prices cover the Trevio platform only. WhatsApp conversation fees charged by Meta, payment gateway fees and usage of
              external AI models connected through your own API keys are billed separately by those providers, at their published rates.
              Prices shown exclude any applicable taxes.
            </p>
          </div>
        </div>
      </section>
      <section style={{ padding: 'clamp(40px,5vw,64px) 0 clamp(88px,10vw,128px)', background: '#FFFFFF' }}>
        <div style={{ maxWidth: 820, margin: '0 auto', padding: '0 24px', display: 'flex', flexDirection: 'column', gap: 40 }}>
          <div style={{ textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 14 }}>
            <span
              style={{
                fontSize: 13,
                fontWeight: 700,
                letterSpacing: '0.12em',
                textTransform: 'uppercase',
                background: 'linear-gradient(90deg,#5B247A,#1BCECF)',
                WebkitBackgroundClip: 'text',
                backgroundClip: 'text',
                color: 'transparent',
              }}
            >
              FAQ
            </span>
            <h2 style={{ margin: 0, fontSize: 'clamp(30px,3.8vw,46px)', lineHeight: 1.1, letterSpacing: '-0.035em', fontWeight: 800 }}>
              Questions, answered.
            </h2>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', borderTop: '1px solid #ECEDF2' }}>
            {faqs.map((q, qI) => (
              <Fragment key={qI}>
                <div style={{ borderBottom: '1px solid #ECEDF2' }}>
                  <button
                    onClick={q.toggle}
                    aria-expanded={q.open}
                    aria-controls={q.id}
                    type="button"
                    style={{
                      width: '100%',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      gap: 16,
                      padding: '22px 4px',
                      background: 'none',
                      border: 'none',
                      cursor: 'pointer',
                      textAlign: 'left',
                      color: '#1A1A2E',
                    }}
                  >
                    <span style={{ fontSize: 17, fontWeight: 700, lineHeight: 1.4 }}>{q.q}</span>
                    <span
                      style={{
                        flex: 'none',
                        width: 32,
                        height: 32,
                        borderRadius: '50%',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        transition: 'all .25s ease',
                        background: q.chevBg,
                      }}
                    >
                      <svg
                        style={{ transition: 'transform .25s ease', transform: q.rot }}
                        width="18"
                        height="18"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="#1BCECF"
                        strokeWidth="2.6"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      >
                        <path d="m6 9 6 6 6-6"></path>
                      </svg>
                    </span>
                  </button>
                  {q.open && (
                    <>
                      <p id={q.id} style={{ margin: 0, padding: '0 52px 24px 4px', fontSize: 15.5, lineHeight: 1.7, color: '#6B7280' }}>{q.a}</p>
                    </>
                  )}
                </div>
              </Fragment>
            ))}
          </div>
        </div>
      </section>
      <section
        style={{
          padding: 'clamp(72px,9vw,112px) 0',
          background: 'linear-gradient(110deg,#5B247A 0%,#8378FF 55%,#5ED6F7 100%)',
          color: '#fff',
        }}
      >
        <div
          style={{
            maxWidth: 880,
            margin: '0 auto',
            padding: '0 24px',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            textAlign: 'center',
            gap: 22,
          }}
        >
          <h2
            style={{
              margin: 0,
              fontSize: 'clamp(34px,4.6vw,58px)',
              lineHeight: 1.06,
              letterSpacing: '-0.04em',
              fontWeight: 800,
              color: '#fff',
              textWrap: 'balance',
            }}
          >
            Not sure which plan fits?
          </h2>
          <p style={{ margin: 0, fontSize: 18.5, lineHeight: 1.6, color: '#fff', maxWidth: 580 }}>
            Talk to our team in Doha and we’ll recommend the right setup for your channels, volume and goals.
          </p>
          <div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: 12, marginTop: 8 }}>
            <a
              className="hv-lift"
              href={SITE.signUpUrl}
              style={{
                whiteSpace: 'nowrap',
                height: 54,
                padding: '0 28px',
                borderRadius: 12,
                display: 'inline-flex',
                alignItems: 'center',
                fontSize: 16,
                fontWeight: 800,
                color: '#5B247A',
                background: '#fff',
                boxShadow: '0 14px 30px -14px rgba(26,10,46,0.6)',
              }}
            >
              Get Started Free
            </a>
            <Link
              className="hv-ghost"
              href="/about#contact-form"
              style={{
                whiteSpace: 'nowrap',
                height: 54,
                padding: '0 26px',
                borderRadius: 12,
                display: 'inline-flex',
                alignItems: 'center',
                fontSize: 16,
                fontWeight: 700,
                color: '#fff',
                border: '1.5px solid #fff',
              }}
            >
              Talk to Sales
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
